### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by AdditionAddict** [CubikNeRubik/angular-electron-typeorm-starter#3]
Hello,

I don't get any typescript warnings and it's hard to see changes. Am I doing something wrond is is this the nature of this starter bundle?

(New to electron and typeorm)

**Comment by CubikNeRubik** [comment]
Hi,

I don't understand your problem. Can you elaborate? Do you speak about hot-reload?

**Comment by AdditionAddict** [comment]
I guess the question boils down to roughly how does your workflow under this starter kit?

So normally in an Angular only framework I run `ng serve` and in Atom editor I make a component. I get typescript warnings if I do something wrong like try to import something that does not exist. I then save and changes render.

Under this starter kit I've being running `npm start`.
I don't get typescript warnings, say when I try to import something that does not exist in Atom.
The console does give warnings when I run `npm start`. But most of the time when I save to correct errors I just get net::ERR_ABORTED.

**Comment by AdditionAddict** [comment]
I've fixed my hot-reload issue using fix here:
https://stackoverflow.com/questions/46709088/angular-electron-app-breaks-on-refresh-or-change

Is there a way to get typescript warnings as I work on a project?

**Comment by CubikNeRubik** [comment]
Looks like some specific error. Because I always got errors related to typescript. In terminal and in Electron window. (I use VS Code on Win 10, maybe this is the reason) 
![image](https://user-images.githubusercontent.com/15522719/59747501-a947c400-9281-11e9-94d1-54100cbee1cb.png)
![image](https://user-images.githubusercontent.com/15522719/59747533-ba90d080-9281-11e9-97a1-ac341371c62a.png)

If you already fix this issue for yourself, can you please make PR with the fix? It can help other people.
Also, add a description of your environment.

**Comment by AdditionAddict** [comment]
Sorry for wasting your time - this seems to be related to my atom environment. **Feel free to close.**

Btw, thank you for this starter bundle! It's really working for me.

On a complete side note, I'd be interested in how this build works / how it was put together in the first place. Are there any good resources or have you done any blog posts on this? I'd be especially interested why everyone elses build seems to rely on python 2 and yours does not.

**Comment by CubikNeRubik** [comment]
Thank you for good words. I don't have any posts about it. I just was required to build a cross-platform application and this starter pack was the first step to it.
